name: Build and test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: License check
        run: mvn -B license:check

      - name: Build and test
        run: |                  
          mvn -B -q install -N
          mvn -B -q install -f shaded-dependencies
          mvn -B -q package -f pulsar-connectors/splunk
          mvn -B -q package -f pulsar-connectors/redis

          for conn in pulsar-connectors/*; do
             if [[ ! -d "$conn" ]]; then continue; fi
             if [[ ! -f "${conn}/pom.xml" ]]; then continue; fi
             if [[ "$conn" == *"camel-"* ]]; then echo "skipping $conn"; continue; fi
             mvn -q -B clean package -f "$conn"
          done
  build-camel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: License check
        run: mvn -B license:check

      - name: Build and test
        run: |                  
          mvn -B -q install -N
          mvn -B -q install -f shaded-dependencies
          mvn -B -q package -f pulsar-connectors/splunk
          mvn -B -q package -f pulsar-connectors/redis

          for conn in pulsar-connectors/*; do
             if [[ ! -d "$conn" ]]; then continue; fi
             if [[ ! -f "${conn}/pom.xml" ]]; then continue; fi
             if [[ "$conn" != *"camel-"* ]]; then echo "skipping $conn"; continue; fi
             mvn -q -B clean package -f "$conn"
          done