name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: License check
        run: mvn -B license:check

      - name: Build and test
        run: |
          mvn -B install -N
          mvn -B install -f shaded-dependencies
          for conn in pulsar-connectors/*; do
             if [ ! -d "$conn" ]; then continue; fi
             if [ ! -f "${conn}/pom.xml" ]; then continue; fi
             cd "$conn"
             mvn -qB clean package
             mvn -qB clean
             cd ../..
          done
